<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Todo;
use Doctrine\ORM\EntityRepository;
use PHPMentors\DomainKata\Entity\EntityInterface;
use PHPMentors\DomainKata\Repository\RepositoryInterface;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends EntityRepository implements RepositoryInterface, PaginationInterface
{
    use PaginationTrait;

    public function add(EntityInterface $entity)
    {
        assert($entity instanceof Todo);
        $this->getEntityManager()->persist($entity);
    }

    public function remove(EntityInterface $entity)
    {
        // TODO: Implement remove() method.
    }


}
